name: client / Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    paths:
      - '.github/workflows/client-lint.yml'
      - 'client/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install Dependencies
        working-directory: client
        run: yarn install --frozen-lockfile

      - name: Lint ESLint
        working-directory: client
        run: yarn lint:eslint

      - name: Lint Prettier
        working-directory: client
        run: yarn lint:prettier

      - name: TypeCheck
        working-directory: client
        run: yarn typecheck
